### ISSUE TITLE
Even though the job is not in the queue, loaner prevents it from being added

### ISSUE THREAD

**Issue by ericgross** [lantins/resque-lock-timeout#17]
I had a job that has been run (or the queue was deleted) but I cannot enqueue the same identifier.

self.loner_enqueue_failed is being called each time.

Could this be related to resque-history (which I am also trying to use, although removing it does not seem to fix this issue)?

**Comment by edjames** [comment]
Hi. 

I was affected by exactly the same issue. I found that when the arguments are a hash instead of just a list of values, the lock key(s) are not properly removed after the job completes i.e. the lock remains in place and is not released.

The easiest solution is to override the `redis_lock_key` method.

I did this:

    def self.redis_lock_key(raw_args)
      args = raw_args.symbolize_keys
      "lock:EncodingsManager::Controller::#{args[:id]}"
    end

That perfectly works for me.

Also, it helps to see what's going on in Redis by running a `redis-cli` session. So try this (assuming you're running Redis locally in dev):

    > redis-cli
    > keys *

That will show you all the keys, and using this you should see keys getting removed after job execution.

Hope that helps.

**Comment by lantins** [comment]
I've never been able to reproduce this problem.

I welcome anyone to provide an example of it breaking in this manor, there is no reason the existing `redis_lock_key` should not work.

@edjames Thanks for feeding back to the project, I'd love to understand _WHY_ overriding the `redis_lock_key` method fixed this for you, please enlighten me if you can :) At the very least, I hope your comment helps someone else (and if thats you, and your reading this, help me figure out _WHY_! :))

**Comment by edjames** [comment]
Honestly, I just haven't had the time to figure out the _why_ in all this. I did what I needed to do to get it working so that I could move on, and unfortunately haven't circled back to figure out why and possibly offer a PR in return.
If/when I ever have time, I'd love to understand this issue more and possibly contribute.

**Comment by lantins** [comment]
I've left issue #26 open to take a look at these things, they may or may not be related.

@edjames Do you deploy on Heroku or similar?

**Comment by edjames** [comment]
We deploy using Ubuntu on AWS - no Heroku, We do process a high volume of jobs though, so I'm 100% confident that whatever my fix actually does, it does it well :grin:

We process several thousand jobs daily without any locking problems using this fix.

**Comment by lantins** [comment]
@edjames Thanks, and can you remember if these workers were being `KILL`ed in the environment? or was it breaking when the job 'failed' for other reasons (ie. something the job depends on went AWOL).

**Comment by edjames** [comment]
From what I remember the lock was never being released. So after flushing Redis, a job would execute once (and write the lock) and then on completion would not clean up the lock.

We were seeing this behaviour even when workers were finishing successfully. We get a very small number of workers getting killed (by the OS) because we have lots of small, quick jobs. The longest job we have will generally take no more than 10 seconds, but usually only around 1-2 seconds per job.

**Comment by edjames** [comment]
I might also add that we are using a managed Elsaticache Redis instance in AWS - we do not self-host Redis. However, in development we _do_ run local instances of Redis and both teh problem and solution were consistent from dev to production.

When we fixed this we were running on Redis version 2.6.

**Comment by lantins** [comment]
Okay, so if the lock was never released, did it eventually timeout? and then the lock was available again?

I'll have a play with this tonight, I'm not overly confident I'll find anything, but I'm going to give it another go!

**Comment by edjames** [comment]
In our case we did not use the lock timeout - that presented us with other problems.

When you're trying it out, be sure to send a hash as the worker parameter, not primitive values (string / integer etc). It was the conversion of the hash into a key that I seem to remember being the source of the problem.
